export { default as TestPositive } from './TestPositive';
export { default as AbsoluteCases } from './AbsoluteCases';
export { default as IncreasedCases } from './IncreasedCases';
export { default as DeathRate } from './DeathRate';
export { default as Total} from './Total';
export { default as Hospitalized } from './Hospitalized';
export { default as SimpleSelect } from './Sortbystate';
export { default as TodayIncreased } from './TodayIncreased';
export { default as TodayDeath } from './TodayDeath';
export { default as RecordList } from './RecordList';
